=== epruesse/ARB/HELP_SOURCE/arb_help.dtd
<!-- ==================================================================== -->
<!--                                                                      -->
<!--   File      : arb_help.dtd                                           -->
<!--   Purpose   :                                                        -->
<!--                                                                      -->
<!--                                                                      -->
<!-- Coded by Ralf Westram (coder@reallysoft.de) in October 2001          -->
<!-- Copyright Department of Microbiology (Technical University Munich)   -->
<!--                                                                      -->
<!-- Visit our web site at: http://www.arb-home.de/                       -->
<!--                                                                      -->
<!--                                                                      -->
<!-- ==================================================================== -->

<!ELEMENT PAGE (UP*,SUB*,TITLE,SECTION*) >
<!ATTLIST PAGE name CDATA #REQUIRED > <!--name of page (equal to filename)-->
<!ATTLIST PAGE edit_warning (release|devel) #REQUIRED > <!--affects the kind of edit-warning which is written into generated help-files-->
<!ATTLIST PAGE source CDATA #REQUIRED > <!--source of helpfile (e.g. 'oldhelp/this.hlp' or 'genhelp/that.hlp' -->

<!ELEMENT UP EMPTY>
<!ATTLIST UP dest CDATA #REQUIRED >
<!ATTLIST UP type (hlp|ps|pdf|email|www) #REQUIRED>
<!ATTLIST UP source_line CDATA #IMPLIED > <!--line no in source file-->
<!ATTLIST UP missing (0|1) #IMPLIED > <!--set to 1 if destination is missing-->

<!ELEMENT SUB EMPTY>
<!ATTLIST SUB dest CDATA #REQUIRED >
<!ATTLIST SUB type (hlp|ps|pdf|email|www) #REQUIRED>
<!ATTLIST SUB source_line CDATA #IMPLIED > <!--line no in source file-->
<!ATTLIST SUB missing (0|1) #IMPLIED > <!--set to 1 if destination is missing-->

<!ELEMENT TITLE (#PCDATA) >

<!ELEMENT SECTION ((T|P|ENUM|LIST)*) >
<!ATTLIST SECTION name CDATA #REQUIRED >

<!ELEMENT ENUM (ENTRY*) >
<!ELEMENT LIST (ENTRY*) >

<!ELEMENT ENTRY ((T|P|ENUM|LIST)*) >
<!ATTLIST ENTRY enumerated CDATA #IMPLIED >
<!ATTLIST ENTRY item CDATA #IMPLIED >

<!ELEMENT P ((T|P|ENUM|LIST)*) >

<!ELEMENT T (#PCDATA|LINK)* >
<!ATTLIST T reflow (0|1) #REQUIRED >

<!ELEMENT LINK EMPTY>
<!ATTLIST LINK dest CDATA #REQUIRED> <!--destination of link (may be other helpfile, email- or web-address)-->
<!ATTLIST LINK type (hlp|ps|pdf|email|www) #REQUIRED>
<!ATTLIST LINK source_line CDATA #IMPLIED > <!--line no in source file-->
<!ATTLIST LINK missing (0|1) #IMPLIED > <!--set to 1 if destination is missing (used for internal links only)-->
<!ATTLIST LINK quoted (0|1) #IMPLIED > <!--set to 0 to avoid quoting of title-->

=== epruesse/ARB/branches/helptest/UNIT_TESTER/run/help/unittest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE PAGE SYSTEM 'arb_help.dtd' [
  <!ENTITY nbsp "&#160;">
  <!ENTITY acute "&#180;">
  <!ENTITY eacute "&#233;">
  <!ENTITY apostr "&#39;">
  <!ENTITY semi "&#59;">
]>

  <!--automatically generated from ../oldhelp/unittest.hlp -->
<PAGE name="unittest" edit_warning="devel">
  <UP dest="arb.hlp" type="hlp" source_line="2"/>
  <UP dest="glossary.hlp" type="hlp" source_line="3"/>
  <SUB dest="aci.hlp" type="hlp" source_line="6"/>
  <SUB dest="srt.hlp" type="hlp" source_line="161"/>
  <TITLE>Unittest example helpfile</TITLE>
  <SECTION name="OCCURRENCE">
    <P>
      <T reflow="1">
        nowhere</T>
    </P>
  </SECTION>
  <SECTION name="DESCRIPTION">
    <P>
      <T reflow="1">
        This is the first paragraph of the description.
        It may be continued on the next line.</T>
    </P>
    <P>
      <T reflow="1">
        Another paragraph
        also
        belonging to description. It is followed by
        an enumeration on the same indentation level:</T>
      <ENUM>
        <ENTRY>
          <T reflow="0">
first enum</T>
          <LIST>
            <ENTRY>
              <T reflow="1">
                Again a paragraph - a one liner followed by an item list. It is completely misplaced at the moment!</T>
            </ENTRY>
            <ENTRY>
              <T reflow="0">
- item 1
- item 2
- item 3
  contains 2 lines</T>
            </ENTRY>
          </LIST>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
   second enum which
   is continued on the next line.
   Currently is misinterpreted as monospaced paragraph.</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            third enum</T>
        </ENTRY>
      </ENUM>
    </P>
  </SECTION>
  <SECTION name="CUSTOM    A custom section.">
    <P>
      <T reflow="1">
        Acts like DESCRIPTION, despite the SECTION line will be part of the headline.
        In DESCRIPTION it would be part of the first paragraph.</T>
    </P>
    <P>
      <T reflow="1">
        First i need to check proper support for different
        indentation levels.</T>
      <LIST>
        <ENTRY>
          <T reflow="1">
            This paragraph has to be indented one level deeper than
            the previous paragraph.</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            That paragraph should be on
            the same level.</T>
          <LIST>
            <ENTRY>
              <T reflow="1">
                Here is another one, even deeper.</T>
            </ENTRY>
            <ENTRY>
              <T reflow="1">
                Same,
                same.</T>
            </ENTRY>
          </LIST>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            Back one step.</T>
          <LIST>
            <ENTRY>
              <T reflow="1">
                One step down - ignoring deeper
                indentation in source.</T>
            </ENTRY>
            <ENTRY>
              <T reflow="1">
                Consecutive paragraphs are only placed on the same
                level if their indentation matches.</T>
            </ENTRY>
            <ENTRY>
              <T reflow="1">
                Using the indentation level used 4 paragraphs above, wont help here.</T>
              <LIST>
                <ENTRY>
                  <T reflow="1">
                    But the "wrong" indentation of the previous
                    paragraph forces this paragraph to get indented one
                    level deeper than the paragraphs before.</T>
                </ENTRY>
                <ENTRY>
                  <T reflow="1">
                    This does not step back.</T>
                </ENTRY>
                <ENTRY>
                  <T reflow="1">
                    same same.</T>
                </ENTRY>
              </LIST>
            </ENTRY>
          </LIST>
        </ENTRY>
      </LIST>
    </P>
    <P>
      <T reflow="1">
        Back to top (end of indentation tests).</T>
    </P>
  </SECTION>
  <SECTION name="Wanted fixes">
    <P>
      <T reflow="1">
        Paragraphs containing multiple spaces will be
        treated as monospaced. This is done to support
        tabular information like the following:</T>
      <P>
        <T reflow="0">
                    other
        column      column
row     1           2
row2    -           3</T>
      </P>
    </P>
    <P>
      <T reflow="1">
        Problems occur if there are empty lines inside such a table, like here:</T>
      <LIST>
        <ENTRY>
          <T reflow="0">
            other
column      column</T>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
row     1           2
row2    -           3</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            (should better be combined)</T>
        </ENTRY>
      </LIST>
    </P>
    <P>
      <T reflow="1">
        Here is some unsupported itemlist:</T>
      <P>
        <T reflow="0">
* item1
  continued on next line
* item2
* item3</T>
      </P>
    </P>
    <P>
      <T reflow="1">
        Itemlist containing paragraphs under some items</T>
      <LIST>
        <ENTRY>
          <T reflow="1">
            - item 1
            - item 2</T>
          <P>
            <T reflow="1">
              This is a short
              description of item 2.
              Currently it does not differ from the items, but it should.</T>
          </P>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            - item 3</T>
          <P>
            <T reflow="1">
              This is a not much longer
              description of item 3.</T>
          </P>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            This is a paragraph which should
            be placed outside the itemlist.
            Currently this is placed like the items above.</T>
        </ENTRY>
      </LIST>
    </P>
    <P>
      <T reflow="1">
        And this paragraph should be back where we were before
        the itemlist began.</T>
    </P>
    <P>
      <T reflow="1">
        Now to sth completely unsupported. It would be nice,
        to support enumerations using letters, since that is
        common, i.e. sth like</T>
    </P>
    <P>
      <T reflow="1">
        A. first enum
        B. 2nd enum
        C. third enum
        D. last enum</T>
    </P>
    <P>
      <T reflow="1">
        should work, but it doesn&apostr;t. Also</T>
      <P>
        <T reflow="1">
          a. first enum
          b. 2nd enum
          c. third enum
          d. last enum</T>
      </P>
    </P>
    <P>
      <T reflow="1">
        should work.</T>
    </P>
    <P>
      <T reflow="1">
        Check some "illegal" itemlists:</T>
      <LIST>
        <ENTRY>
          <T reflow="1">
            ----------------------</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            -noitem</T>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
-  eithernoitem</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            **********************</T>
        </ENTRY>
        <ENTRY>
          <T reflow="1">
            *noitem</T>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
*  eithernoitem</T>
        </ENTRY>
      </LIST>
    </P>
  </SECTION>
  <SECTION name="FEATURE TESTS">
    <P>
      <T reflow="1">
        Here all existing helpfile features should be tested:</T>
      <LIST>
        <ENTRY>
          <T reflow="0">
- first testing an inlined
  link to another help file: <LINK dest="srt.hlp" type="hlp" source_line="163"/>
          </T>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
- and a link to the arb homepage
  <LINK dest="http://www.arb-home.de/" type="www" source_line="166"/>
  followed by text.
          </T>
        </ENTRY>
        <ENTRY>
          <T reflow="0">
- arb help also supports mail-links (like <LINK dest="devel@arb-home.de" type="email" source_line="170"/>).
  All 3 sorts of links should be clickable in the html version.
          </T>
        </ENTRY>
      </LIST>
    </P>
  </SECTION>
  <SECTION name="NOTES">
    <P>
      <T reflow="1">
        Note that this test may help me.</T>
    </P>
  </SECTION>
  <SECTION name="EXAMPLES">
    <P>
      <T reflow="1">
        The whole file is just an example.</T>
    </P>
  </SECTION>
  <SECTION name="WARNINGS">
    <P>
      <T reflow="1">
        This text wont help you.</T>
    </P>
    <P>
      <T reflow="1">
        Even if i add more paragraphs here,
        it will not get more useful.</T>
    </P>
  </SECTION>
  <SECTION name="BUGS">
    <P>
      <T reflow="1">
        will be detected by the unit test
        checking the files into which
        this file gets converted.</T>
    </P>
  </SECTION>
</PAGE>
